blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/omerakben/transit-to-open-source-tuel/security/policy
    about: Please review the security policy and use the private disclosure process.
  - name: Support
    url: https://github.com/omerakben/transit-to-open-source-tuel/blob/main/SUPPORT.md
    about: Read our support guidelines for help channels.
