name: Feature request
description: Suggest an idea or enhancement for the TUEL test framework.
title: "[Enhancement]: "
labels:
  - enhancement
  - needs-triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping shape the project! Tell us about the problem you'd like to solve.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a clear and concise description of the proposed improvement.
      placeholder: It would be great if...
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Explain the user or business value behind this feature.
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Describe your suggested approach. Include API changes, new configuration options, or test coverage expectations if applicable.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any alternative solutions or workarounds you have considered.
  - type: input
    id: impacted_areas
    attributes:
      label: Impacted areas
      placeholder: e.g., API tests, UI tests, configuration, documentation
  - type: checkboxes
    id: checklist
    attributes:
      label: Contributor checklist
      options:
        - label: I have checked the roadmap and existing issues for similar requests
          required: true
        - label: I am willing to help implement this feature
